const ENV = process.env

export const NODE_URL = ENV.REACT_APP_NODE_URL
export const GOOGLE_API_KEY = ENV.REACT_APP_GOOGLE_API_KEY
export const GA_TRACKING_CODE = ENV.REACT_APP_GA_TRACKING_CODE
export const HASURA_URL = ENV.REACT_APP_HASURA_URL
export const HASURA_WSS = ENV.REACT_APP_HASURA_WSS
export const HASURA_KEY = ENV.REACT_APP_HASURA_KEY
export const TELEGRAM_TOKEN = ENV.REACT_APP_TELEGRAM_TOKEN
export const ABA_PAYWAY_MERCHANT_ID = ENV.REACT_APP_ABA_PAYWAY_MERCHANT_ID
export const DECRYPTED_SECRET_KEY = ENV.REACT_APP_DECRYPTED_SECRET_KEY
